version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: "updates"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    reviewers:
      - jochemkeller
    assignees:
      - jochemkeller
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
