name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: NPM install
        run: npm install

      - name: Run ESLint
        run: npm run eslint

      - name: Run TypeScript checker
        run: "npm run check:types"

      - name: Run CasePolice
        run: "npm run check:case:fix"

      # - name: Run tests
      #   run: npm run test
